### ISSUE TITLE
No way to access stage variables

### ISSUE THREAD

**Issue by rochdev** [dougmoscrop/serverless-http#11]
We use stage variables to configure remote endpoints that are used by our lambda. Currently there is no way to access those from express using this library.

**Comment by rochdev** [comment]
Looks like [res.locals](http://expressjs.com/en/api.html#res.locals) could be used to store stage variables.

**Comment by dougmoscrop** [comment]
Yep. Another option would be putting the entire lambda request and context
on via _propertyName

**Comment by rochdev** [comment]
Seems like AWS approach is to serialize the entire event and context in headers.

See https://github.com/awslabs/aws-serverless-express/blob/master/index.js#L33

**Comment by rochdev** [comment]
If you confirm the headers solution is acceptable I'll make a PR by next week. This way the app can be compatible with both this library and the one from AWS.

**Comment by dougmoscrop** [comment]
Hmmmm.. One of the reasons I wrote this library was to avoid
reserialization..Their approach requires reserialization the entire
request...

I would attach them to req as objects for sure. What about introducing
options: serverlessHttp(app, { options }) and making adding that
information to the headers optional?



On Thu, Jan 19, 2017, 9:29 AM Roch Devost <notifications@github.com> wrote:

Seems like AWS approach is to serialize the entire event and context in
headers.

See
https://github.com/awslabs/aws-serverless-express/blob/master/index.js#L33

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/dougmoscrop/serverless-http/issues/11#issuecomment-273790232>,
or mute the thread

**Comment by rochdev** [comment]
That would make sense.

Also, one of the options could be a function to hook into the request creation to customize it. This way anyone that wants the same result without serializing the entire `event` object would be able to do it.

**Comment by dougmoscrop** [comment]
Done via 1.3 (in the sense that the original event and context are available on req, and you can specify a request: transform function)

**Comment by rochdev** [comment]
@dougmoscrop Hope I'm not too late on this, but what I had in mind was more something like this:

```js
transform: (event, context) => (req, res) => {
  // modify req/res as needed
}
```

which removes the need to pollute the request object

**Comment by rochdev** [comment]
@dougmoscrop Will do, but since a new version has already been released, I am not sure how to keep backward compatibility with 1.3.0

**Comment by dougmoscrop** [comment]
well, you could just add a new thing, this transform option. Ignore my request/response ones. I will deprecate them or whatever;

I don't think this library is popular enough such that people have already jumped on to these new features so not a big deal this time around
