### ISSUE TITLE
AWS Lambda time out when using `connect-dynamodb`

### ISSUE THREAD

**Issue by neverendingqs** [dougmoscrop/serverless-http#19]
When attempting to use `connect-dynamodb`, a DynamoDB-backed [session middleware for express](https://github.com/expressjs/session), the AWS Lambda function times out according to the logs.

I traced it down and it seems to be calling [callback](https://github.com/dougmoscrop/serverless-http/blob/bab48728470311bcfc89b1b5e75cc23880857dcc/serverless-http.js#L37) properly, so not sure exactly what's happening. I did not encounter this issue when I switched over to https://github.com/awslabs/aws-serverless-express.

I'm not sure if this is an intended use case for this library, but if it is I have a snapshot of the code before switching over: https://github.com/hbcwr/pco-schedule-swapper/tree/bookmark/serverless-http.

**Comment by dougmoscrop** [comment]
Do you have any more details about your testing/debugging that you can share?

**Comment by neverendingqs** [comment]
Sorry forgot to include: the session information made it into the DynamoDB table even though the Lambda times out. When I removed `connect-dynamodb` (so just using the default in-memory session), I get a response. It seems to be tripping up on something `connect-dynamodb` is doing, but I didn't see anything wrong with `connect-dynamodb`.

I mostly littered `console.log()` statements everywhere right up to the `callback()` call, including inside `connect-dynamodb`, but I didn't see anything fishy.

**Comment by dougmoscrop** [comment]
The reason for this is `connect-dynamodb` has a setInterval call:

https://github.com/ca98am79/connect-dynamodb/blob/master/lib/connect-dynamodb.js#L62

By default, `callback` mode of lambda invocation waits for the event loop to be empty. in this case it will never be empty. The awslabs module uses the legacy context.succeed/fail which does not wait for the event loop.

There's a flag to make callback work the same. I'm torn between using it, and thus behaving like the awslabs library or leaving it as is because I think this is a sign that your application has a bug/smell in it (for serverless use). The problem is what does that setInterval do? Why is there a 'background job' on an API tier? It will 'work' I guess, but it will only run when the process is unfrozen.

**Comment by neverendingqs** [comment]
Thanks @dougmoscrop. Setting `options.reapInterval` to -1 skipped the `setInterval()` call, and resolved this issue. It was a lack of experience on my part in not being able to identify that the event loop isn't empty.

> I think this is a sign that your application has a bug/smell in it (for serverless use)

I agree. I did not fully understand what `reapInterval` was doing. With the advent of [DynamoDB TTL](https://aws.amazon.com/blogs/aws/category/amazon-dynamo-db/), that should be the way to go for killing sessions. (Mostly commentary that's not fully related to this library).
