### ISSUE TITLE
unclear if PUT body is properly forwarded... not sure how to debug

### ISSUE THREAD

**Issue by refacktor** [dougmoscrop/serverless-http#256]
I'm trying to use `serverless-http` to create a serverless deployment of `pouchdb-server` on top of AWS Lambda with Elastic Filesystem.

My solution is here: https://github.com/refacktor/pouchdb-aws-serverless

I'm currently able to get the standard PouchDB response with a `curl -X GET ...` and was able to create a database by using `curl -X PUT https://.../db1`.

But when I try to PUT a document  with:

`curl -X PUT https://XXXXXXXXX.execute-api.us-west-2.amazonaws.com/prod/db1/doc1 -d '{"hello":"world", "_id":"doc1"}'
`
I get:
`{"error":"missing_id","reason":"_id is required for puts"}`

My best guess here is that the PUT body is not getting forwarded by `serverless-http`, but I'm unsure how to troubleshoot further.

**Comment by gsecret054** [comment]
Hi,
This is Francisco M. from Freelancer.com:
https://www.freelancer.com/u/francmart514

I've applied to your job posting and I wonder if you have tried this issue conclusion below:
https://github.com/pouchdb/pouchdb/issues/4913

As a fully dedicated developer, I'd like to help you out, and also want a long-term relationship.
Hope your warm attention.

All the best!

**Comment by dougmoscrop** [comment]
The first thing I'd check is whether or not a proper Content-Type header is required so that the express-pouchdb component knows the body is JSON, otherwise it's just getting the actual string `{"hello":...`

You could of course force it to assume the request is always json by using a [request transformation](https://github.com/dougmoscrop/serverless-http/blob/master/docs/ADVANCED.md#transformations) assuming that is the issue!

**Comment by refacktor** [comment]
@dougmoscrop yes indeed, adding a `-H "Content-Type: application/json"` solves the problem! Although I don't fully understand why... we can close this issue. When using the component through normal http, the header is not required.
