### ISSUE TITLE
Use with Serverless Dashboard V2.0 and CLI V3

### ISSUE THREAD

**Issue by patricktyndall** [dougmoscrop/serverless-http#290]
Hello all. Serverless Inc just "upgraded" my app to a new version of their Dashboard product, breaking (in prod) a ton of this library's functionality which we were using.

For example, `getDashboardUrl` now returns URLs that are incorrect for their new dashboard (I have tried upgrading to 3.2.0, and am currently deploying code with serverless cli v3.35.0).
- We were previously using v2.6.0 of this library and v2 of serverless-cli with no issues.

In general, I'm wondering:
- What is the status of this library? Is this still officially supported by Serverless? I see the lib is being updated, but I can't find any official content besides the 2017 blog post.
- Has this library been updated for the Dashboard V2.0 and CLI V3 releases? Is there a compatibility chart or other compatibility constraints?

Thanks for the work. I love the idea of this stack but breaking rollouts like cause a fair amount of frustration.

**Comment by dougmoscrop** [comment]
This library has never been supported by Serverless, so just want to confirm that this is the right repo?

**Comment by patricktyndall** [comment]
Thanks, good to know - right repo, figured some level of endorsement based on pages/posts on serverless.com.

Sorry to express serverless-related frustration here. Are you aware of recent changes /. what is your outlook?

**Comment by dougmoscrop** [comment]
Sorry just to be clear, even though it's not supported by serverless, if you can help me understand how this library is no longer working as expected, I might still be able to help.  This library is a very thin wrapper around the payload format that AWS Lambda passes off to functions, and the in-memory representations of Node.js' HTTP request/response objects, in order to run regular Nodejs web frameworks inside of Lambda, so when you say `getDashboardUrl` returns incorrect URLs (do you mean formatted incorrectly? like invalid? or they go to 404s?) I don't understand what this library is doing with the Dashboard.

**Comment by patricktyndall** [comment]
Thanks & makes sense. All of the lambda <> web framework middleware still works (& sounds like it's decoupled from serverless / serverless SDK, which is great to hear)

The links from `getDashboardUrl` 404 -- the Serverless Dashboard itself has changed, so URLs are now structured differently (the urls still look the same, they just no longer resolve since Serverless moved their website around).

Not sure if you actively use serverless.com, but you can see it's been updated. I got an email this morning announcing the change.
