### ISSUE TITLE
Typescript Definitions?

### ISSUE THREAD

**Issue by awwong1** [dougmoscrop/serverless-http#64]
Is there any interest in adding typescript definition files to this project?
I currently have a working definitions file that I submitted to DefinitelyTyped but perhaps it would be better to make it more generic move it here instead.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31284

**Comment by welkie** [comment]
I'm familiar with TypeScript and I could help maintain type definitions in this repo if the owner agrees to have type definitions live here.

**Comment by dougmoscrop** [comment]
I don't use TypeScript but I certainly want to support what people need

**Comment by dougmoscrop** [comment]
Sounds great, I think 2 is fine given the size of this project; I don't intend on changing the interface very much.

I have some code where I started to already refactor the main .js file to support multiple providers, I will try to push this soon, I just got back from vacation so I am catching up at work.

**Comment by welkie** [comment]
Sounds good. No rush, I'll mainly have time to submit PRs on weekends. One thing I was going to suggest when I got in touch with you is that it would make sense for it to eventually be a breaking change to support multiple providers, so that instead of this:
```
const awsAdapter = require('serverless-http');
const gcpAdapter = require('serverless-http').gcp;
```
You would have this:
```
const awsAdapter = require('serverless-http').aws;
const gcpAdapter = require('serverless-http').gcp;
```
And it would treat each provider as a first class citizen. But in the mean time, you could always alias `.aws` to importing the library itself, to defer that breaking change.

**Comment by dougmoscrop** [comment]
Yep, although I had been thinking we might want to pass the provider in as an argument, something like:

```js
const serverless = require('serverless-http');

module.exports = serverless(app, {
  provider: process.env.PROVIDER
});
```

That way if you were using say Serverless, you could set the environment up to the provider name and deploy the same code. I don't personally use multi-provider/etc but it seems harmless as a convention?

**Comment by welkie** [comment]
I think that either API would work to achieve that goal. Mine would simply be rewrote to `require('serverless-http')[process.env.PROVIDER]`. But I actually like your style better anyways now that I see it, because there may be more parameters you would want in the future to determine what "adapter" object is returned by the `serverless` function in your snipper. Ex. a parameter for people to specify the middleware framework (Express, Koa, etc) so that it would rely less on this library inferring the middleware framework by examining the `app` object. If frameworks start to become too similar, it might get hard to infer the middleware framework.

**Comment by dougmoscrop** [comment]
Multi-provider foundation is in main, and typescript defs too, closing this
