### ISSUE TITLE
General Question on callbackWaitsForEmptyEventLoop 

### ISSUE THREAD

**Issue by selected-pixel-jameson** [dougmoscrop/serverless-http#95]
Hello,

I know that this isn't really the place to pose this question, but I'm not sure where else to put it. I have a project that is using this module along with express and sequelize connecting to an RDS Postgres instance. Right now when I do load testing I'm seeing the RDS instance holding on to connections for 30 minutes before expiring them. This is causing issues as I'm hitting the database connection limits within RDS. 

I've read a ton of documentation on how to efficiently use lambda functions along with sequelize and that I should be implementing context.callbackWaitsForEmptyEventLoop  = false, which seems to be the default for serverless-http. 

Also I have my pool settings set as such:
```
"pool": {
      "max": 1,
      "min": 0,
      "idle": 1000
    }
```

The only other thing that I've read is that I'm supposed to open the connection to the database outside of the handler function. I guess I'm not sure how to do that or if it's even possible using this plugin. If anyone has any advice or has gone through this issue before all suggestions are welcome. 

Thank you!

**Comment by dougmoscrop** [comment]
Hmm, a few things:

- As of 2.x, this library doesn't use the callback at all, so callbackWaitsForEmptyEventLoop is sort of N/A -- it literally is only when you use callback() that this matters, if you use async/return a promise, the handler resolves as soon as that happens. But yes, if you do use callback, you want to make sure there are no stray timers or other event emitters keeping the event loop open (using timer.unref() can be useful)

~- Since Lambdas are single execution units, I would think you want to configure the pool size to be 1.  Then you only have as many open connections to the database as you have active Lambda functions~
Looks like you got that covered

- Connecting to the database outside is a good idea, and is somewhat orthogonal to using this library, e.g.:

Suboptimal:

```js
module.exports.handler = async (event) => {
  // will incur the overhead of the connect every time
  const connection = await createConnection(url);
  await doStuff(connection);
};
```

Better:

```js
// don't use reject, otherwise you get unhandled rejection errors
const connect = new Promise(async resolve => {
  try {
    resolve(await createConnection());
  } catch (err) {
    // log your err
   resolve(null);
});

module.exports.handler = async (event) {
  // you still await, but most of the time the promise will already be resolved
  const connection = await connect;
  if (connection) {
    await doStuff(connection);
  } else {
    throw new Error('No DB connection!')
  }
}
```

Best:

< your nifty code with retry logic and connection reestablishment >

This eager-async pattern can show up anywhere in your code, doesn't have to be in the "handler" (you can have it deep in some driver class or your data layer).

That said, this library just returns a function, so you can totally do:

```js
const handle = serverless(app);

module.exports = async event => {
  // stuff before
  const result = await handle(event);
  // stuff after
  return result;
};
```

But in this case I don't think that's entirely necessary

**Comment by dougmoscrop** [comment]
That said - if you're still exhausting your connection limits then you've gotta further tighten that idle period to really low, and have that "eager async" logic handle reconnecting and so on, or, limit your concurrency.  If your API needs to have 1000 lambdas running you need to support 1000 connections or you will just be burning $ spinning CPU cycles waiting for a connection to open... ideally, set a reasonable concurrency limit and have whatever is talking to your API understand retries.

**Comment by selected-pixel-jameson** [comment]
Wow. Thank you for such a detailed response. Let me try to understand all this and I'll get back to you. Just realized I wasn't even running the latest version.

**Comment by dougmoscrop** [comment]
No worries, what version of sequelize are you using?  Looks like they had all kinds of pool shenanegans that they fixed with https://github.com/sequelize/sequelize/pull/10051 ?

**Comment by selected-pixel-jameson** [comment]
It just seems as if the database connections aren't being terminated on a timely basis at all. At this point I'd be fine with it not maintaining any database connection. Going to give this a try..
const handler = serverless(app)
```
module.exports.handler = async (event, context) => {
  // you can do other things here
  context.callbackWaitsForEmptyEventLoop = false
  const result = await handler(event, context)
  // and here
  return result
}
```

**Comment by dougmoscrop** [comment]
Hmm, I wonder if the problem if the Lambda is going to sleep before the pool has a chance to free the connection..

**Comment by selected-pixel-jameson** [comment]
I just can't peg it. This is an example of the db connections from RDS. 
https://cloudup.com/cveUNULipdd

It's odd because nothing else is using the RDS instance and the connections seem to get half'd in 5 minute intervals until they are all disconnected. It's very odd.

**Comment by dougmoscrop** [comment]
Hey, sorry - so as this point I think it's worth asking on AWS support forums, etc. about best practices from Lambda to RDS (I would just focus on a simple Lambda function that has no other complexities like express or this library in it) and go from there.
